#!/bin/bash
set -e
eval "$($(dirname $0)/adr-config)"

source "$(dirname $0)/_adr_database"

## usage: adr generate index
##
## Generates an index and a table of contents in asciidoc

function listByFieldWhereX() {
  cat <<EOF
== $1

[cols="3,1,1,1,1", options="header"]
|===
|Name
|Proposed Date
|Decision Date
|Status
|Priority

EOF

  echo $(selectFromDatabase "SELECT '|' || title, proposed, decision, status, priority FROM adr WHERE ${2}")

  echo "|==="
  echo
}


function includeAllADRs() {

  for (( i=0; i < ${#ADR_LIST[@]}; i+=6 ))
  do
    local fileref="${ADR_LIST[$i+5]}"
    fileref="${fileref:31}"
    echo "include::${fileref}[]"
    echo " "
  done

}

#################
# Actual output #
#################

cat <<EOF
//////////////////////////////////////////////////////////////
/                                                            /
/ Do not change this file - all changes will be overwritten! /
/                                                            /
//////////////////////////////////////////////////////////////
EOF

# List by SLA
listByFieldWhereX "List of all ADR due in 14 day" "status = 'proposed' and date('now') < date(proposed, '+14 day')"

# List by status
listByFieldWhereX "List of all drafted ADR" "status = 'drafted'"

listByFieldWhereX "List of all proposed ADR" "status = 'proposed'"

listByFieldWhereX "List of all accepted ADR" "status = 'accepted'"

listByFieldWhereX "List of all superseded ADR" "status = 'superseded'"

listByFieldWhereX "List of all rejected ADR" "status = 'rejected'"

# List by priority
listByFieldWhereX "List of all ADR with low priority" "priority = 'low'"

listByFieldWhereX "List of all ADR with medium priority" "priority = 'medium'"

listByFieldWhereX "List of all ADR with high priority" "priority = 'high'"

# All
listByFieldWhereX "List of all ADR" "status = status"


echo  "== ADR List"

echo  ":leveloffset: +2"

#includeAllADRs

# Use last-update-label of generated index
cat <<EOF
  Last update: $(date -u +'%Y-%m-%d %H:%M')
EOF
